config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#profile"
  get "/about", to: "pages#about"

  resources :users, only: %i[index edit update show] do
    collection do
      get :profile
    end
  end

  resources :connections, only: %i[new create destroy]
  resources :groups do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :connections
  has_many :contacts, through: :connections, source: :user, foreign_key: :contact_id
  has_many :groups
  has_many :messages

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :first_name, :last_name, :address, presence: true
  validates :phone, length: { maximum: 15 }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  before_save :set_timezone_and_offset

  def set_timezone_and_offset
    timezone_obj = Timezone.lookup(latitude, longitude)
    self.timezone = timezone_obj.name
    self.offset = timezone_obj.utc_offset / 3600 # from seconds to hours
  end

  def all_contacts
    connections.map(&:contact) # connections.map { |connection| connection.contact }
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def working_hours_validity
    if (working_hour_start.present? && working_hour_end.present?) && (working_hour_start < working_hour_end)
      errors.add(:working_hour_start, "must be before working_hour_end")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
    @contact = User.find(params[:id])
    # Adjust offset only for contact timezone
    user_offset = current_user.offset - @contact.offset
    @contact.working_hour_start = adjust_to_24_hours(@contact.working_hour_start + user_offset)
    @contact.working_hour_end = adjust_to_24_hours(@contact.working_hour_end + user_offset)

    # Adjust offset for all conections
    @connections = Connection.where(user: current_user)
    @groups = Group.where(user: current_user)
    @availabilities = [current_user]
    @connections.each do |connection|
      user_offset = current_user.offset - connection.contact.offset
      connection.contact.working_hour_start = adjust_to_24_hours(connection.contact.working_hour_start + user_offset)
      connection.contact.working_hour_end = adjust_to_24_hours(connection.contact.working_hour_end + user_offset)
      @availabilities.push(connection.contact)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.nil?
      redirect_to root_path, alert: "User not found!"
    end

    if @user.update(user_params)
      redirect_to url_from(@user) || user_url(@user), notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "Account was successfully destroyed.", status: :see_other
  end

  def profile
    @user = User.find(current_user.id)
    @connections = Connection.where(user: current_user)
    @groups = Group.where(user: current_user)
    @other_groups = Group.where("contact_ids @> ?", "{ #{current_user.id} }")
    @availabilities = [current_user]
    @connections.each do |connection|
      user_offset = current_user.offset - connection.contact.offset
      connection.contact.working_hour_start = adjust_to_24_hours(connection.contact.working_hour_start + user_offset)
      connection.contact.working_hour_end = adjust_to_24_hours(connection.contact.working_hour_end + user_offset)
      @availabilities.push(connection.contact)
    end
  end

  # Methods to convert timezones
  def set_connections_availability
    @connections = Connection.where(user: current_user)
    @availabilities = [current_user]
    @connections.each do |connection|
      user_offset = current_user.offset - connection.contact.offset
      connection.contact.working_hour_start = adjust_to_24_hours(connection.contact.working_hour_start + user_offset)
      connection.contact.working_hour_end = adjust_to_24_hours(connection.contact.working_hour_end + user_offset)
      @availabilities.push(connection.contact)
    end
  end

  def adjust_to_24_hours(hour)
    if hour > 23
      hour -= 24
    elsif hour.negative?
      hour += 24
    end
    hour
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :working_hour_start, :working_hour_end,
      :timezone, :phone, :latitude, :longitude, :address, :offset)
  end
end

app/views/users/edit.html.erb
<div class="global" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1636955816868-fcb881e57954?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);">
  <div class="edit-cointainer">
    <h1 class="titleedit mx-1 my-1 p-5"> <%= image_tag "userprofile.png" %> Edit profile </h1>
      <div id="formedit">
        <div class="container row justify-content-center ">
            <%= simple_form_for @user do |f| %>
              <%= f.input :address %>
              <%= f.input :working_hour_start %>
              <%= f.input :working_hour_end %>
                <%= f.button :submit, class: "btn btn-primary my-3 d-flex" %>
            <% end %>
        </div>
      </div>
  </div>

  <div class="edit-cointainer2" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1599930113854-d6d7fd521f10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1180&q=80);">

  <div>
</div>

app/views/users/index.html.erb
<div class="groups">
  <div>
    <h4 class="bg-light p-4 my-2 border-top border-bottom d-flex justify-content-end fw-bold">My Groups</h4>
    <h6 class="bg-light p-2 border-top border-bottom">Web Dev group</h6>
    <ul class="list-group list-group-light mb-5">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <img src="https://mdbootstrap.com/img/new/avatars/8.jpg" alt="" style="width: 45px; height: 45px"
          class="rounded-circle" />
        <div class="ms-3">
          <p class="fw-bold mb-1">Bruno Fazz</p>
          <p class="text-muted mb-0">john.doe@gmail.com</p>
        </div>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <img src="https://mdbootstrap.com/img/new/avatars/6.jpg" class="rounded-circle" alt=""
          style="width: 45px; height: 45px" />
        <div class="ms-3">
          <p class="fw-bold mb-1">Anne Bortoli</p>
          <p class="text-muted mb-0">alex.ray@gmail.com</p>
        </div>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <img src="https://mdbootstrap.com/img/new/avatars/7.jpg" class="rounded-circle" alt=""
          style="width: 45px; height: 45px" />
        <div class="ms-3">
          <p class="fw-bold mb-1">Kate Hunington</p>
          <p class="text-muted mb-0">kate.hunington@gmail.com</p>
        </div>
      </div>
    </li>
    </ul>
  </div>
  <h6 class="bg-light p-2 border-top border-bottom">Design group</h6>
  <ul class="list-group list-group-light">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <img src="https://mdbootstrap.com/img/new/avatars/9.jpg" alt="" style="width: 45px; height: 45px"
        class="rounded-circle" />
      <div class="ms-3">
        <p class="fw-bold mb-1">Ara Gallardo</p>
        <p class="text-muted mb-0">soraya.letto@gmail.com</p>
      </div>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <img src="https://mdbootstrap.com/img/new/avatars/11.jpg" class="rounded-circle" alt=""
        style="width: 45px; height: 45px" />
      <div class="ms-3">
        <p class="fw-bold mb-1">Zeynep Dudley</p>
        <p class="text-muted mb-0">zeynep.dudley@gmail.com</p>
      </div>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <img src="https://mdbootstrap.com/img/new/avatars/15.jpg" class="rounded-circle" alt=""
        style="width: 45px; height: 45px" />
      <div class="ms-3">
        <p class="fw-bold mb-1">Ayat Black</p>
        <p class="text-muted mb-0">ayat.black@gmail.com</p>
      </div>
    </div>
  </li>
  </ul>
</div>

<div id="chatbox">
	<div id="friendslist">
    <div id="topmenu">
        <span class="friends"></span>
    </div>

    <div id="friends">
      <div class="friend">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/1_copy.jpg" />
        <p><strong>Bruno Fazz</strong>
        <span>Available</span>

        <div class="status available"></div>
      </div>

    <div class="friend">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/2_copy.jpg" />
        <p>
          <strong>Martin Joseph</strong>
          <span>marjoseph@gmail.com</span>
        </p>
        <div class="status away"></div>
    </div>

    <div class="friend">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/3_copy.jpg" />
        <p>
          <strong>Tomas Kennedy</strong>
          <span>tomaskennedy@gmail.com</span>
        </p>
        <div class="status inactive"></div>
    </div>

    <div class="friend">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/4_copy.jpg" />
        <p>
          <strong>Enrique	Sutton</strong>
          <span>enriquesutton@gmail.com</span>
        </p>
        <div class="status inactive"></div>
    </div>

    <div class="friend">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/5_copy.jpg" />
        <p>
        <strong>	Darnell	Strickland</strong>
          <span>darnellstrickland@gmail.com</span>
        </p>
        <div class="status inactive"></div>
    </div>
    <div id="search">
        <input type="text" id="searchfield" value="Search contacts..." />
    </div>

  </div>

<%# <h3>All Users</h3>
<p>here we can see all of our app users</p> %>

<%# <% @users.each do |user| %>
  <%# <p>Name: <%= user.first_name <%= user.last_name</p> %>
<%# <% end  %>

app/views/users/profile.html.erb
<div class="global" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1636955816868-fcb881e57954?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);">
  <div class="groups">
    <div class="groupone">
      <div class="accordion" id="accordionExample">
        <h4 class="my-groups bg-light py-4 d-flex justify-content-center fw-bold">My Groups &nbsp;<%= image_tag "team.png" %></h4>

          <% @groups.each do |group| %>
            <div class="accordion-item">
              <h6 class="accordion-header bg-light p-2 border-top border-bottom">
                <div class="accordion collapsed" data-bs-toggle="collapse" data-bs-target="#collapseOne<%= group.id %>" aria-expanded="false" aria-controls="collapseOne<%= group.id %>">
                  <div class="lista d-flex justify-content-between px-2">
                    <div><%= group.title %> <i class="fa-solid fa-crown" style="color: #c7a423;"></i></div>
                    <div class="threeicons">
                      <%= link_to edit_group_path(group), class: "link-with-icon" do %><i class="fa-regular fa-pen-to-square"></i><% end %>
                      <%= link_to group_path(group), class: "link-with-icon" do %><i class="fa-regular fa-comment"></i><% end %>
                    </div>
                  </div>
                </div>
            </h6>
            <div id="collapseOne<%= group.id %>" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="">
              <div class="accordion-body">
                <ul class="list-group list-group-light mb-5">
                  <% group.contact_ids.each do |member| %>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      <div class="d-flex align-items-center">
                        <% user = User.find(member)  %>
                        <%= image_tag "#{user.image}", class: "avatar", alt: "dropdown menu" %>
                        <div class="ms-3">
                          <p class="fw-bold mb-1">
                            <%= "#{user.first_name} #{user.last_name}" %>
                          </p>
                          <p class="text-muted mb-0">
                            <%= user.email %>
                          </p>
                        </div>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
      </div>
    </div>

    <div class="grouptwo">
      <div class="accordion" id="accordionExample">
          <% @other_groups.each do |group| %>
            <div class="accordion-item">
                <h6 class="accordion-header bg-light p-2 border-top border-bottom">
                  <div class="accordion collapsed" data-bs-toggle="collapse" data-bs-target="#collapseOne<%= group.id %>" aria-expanded="false" aria-controls="collapseOne<%= group.id %>">
                    <div class="lista d-flex justify-content-between px-2">
                      <%= group.title %>
                      <div>
                        <%= link_to group_path(group), class: "link-with-icon" do %><i class="fa-regular fa-comment"></i><% end %>
                      </div>
                    </div>
                  </div>
                </h6>
                <div id="collapseOne<%= group.id %>" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="">
                  <div class="accordion-body">
                    <ul class="list-group list-group-light mb-5">
                    <%# SHOW USER OWNER %>
                      <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                          <% user = User.find(group.user_id)  %>
                          <%= image_tag "#{user.image}", class: "avatar", alt: "profile photo" %>
                          <%# <img src="#{user.image}" class="rounded-circle" alt="" style="width: 45px; height: 45px" /> %>
                            <div class="ms-3">
                              <p class="fw-bold mb-1">
                                <%= "#{user.first_name} #{user.last_name}" %>
                              </p>
                              <p class="text-muted mb-0">
                                <%= user.email %>
                              </p>
                              </div>
                            </div>
                        </li>
                      <% group.contact_ids.each do |member| %>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                          <div class="d-flex align-items-center">
                            <% user = User.find(member)  %>
                            <%= image_tag "#{user.image}", class: "avatar", alt: "profile photo" %>
                            <%# <img src=user.image class="rounded-circle" alt="" style="width: 45px; height: 45px" /> %>
                            <div class="ms-3">
                              <p class="fw-bold mb-1">
                                <%= "#{user.first_name} #{user.last_name}" %>
                              </p>
                              <p class="text-muted mb-0">
                                <%= user.email %>
                              </p>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
          <% end %>
      </div>
    </div>
  </div>

  <div id="chatbox">
    <div id="friendslist">
      <div id="topmenu">
          <div id="gradient"></div>
            <div class="searchbox">
                <input type="search" id="searchBar" onkeyup="searchFriends()" placeholder="Search contacts...">
                  <button type="submit" value="search">&nbsp;</button>
                  <div class="minicons">
                    <%= image_tag "utc.png" %>
                    <%= image_tag "placeholderr.png" %>
                  </div>
            </div>
      </div>
      <% @connections.each do |connection|  %>
        <div class="friend">
          <a href="<%= user_path(connection.contact) %>">
          <%= image_tag "#{connection.contact.image}", class: "avatar", alt: "dropdown menu" %>
          <p class="contactshow d-flex justify-content-between">
            <strong><%= "#{connection.contact.first_name} #{connection.contact.last_name}" %></strong></p>
              <p class="contactshow2 d-flex justify-content-between">
                <span class="badge badge-info" style="background-color: #6C757D; border-radius: 30px; color: #fff; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande',
    'Lucida Sans', Arial, sans-serif;"> <%= connection.contact.working_hour_start%>:00 | <%= connection.contact.working_hour_end%>:00</span>
              </p>
            <p class="contactshow2">
              <span class="badge badge-info" style="background-color: #17A2B8; border-radius: 30px; color: #fff; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;">
              <%= connection.contact.timezone%>
              </span>
            </p>
        </div>
      <% end %>

<script>
  function searchFriends() {
    var input = document.getElementById("searchBar");
    var filter = input.value.toUpperCase();
    var friends = document.getElementsByClassName("friend");

    for (var i = 0; i < friends.length; i++) {
      var friend = friends[i];
      var name = friend.getElementsByTagName("strong")[0].innerText.toUpperCase();

      if (name.includes(filter)) {
        friend.style.display = "";
      } else {
        friend.style.display = "none";
      }
    }
  }
</script>

app/views/users/show.html.erb
<div class="global" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1636955816868-fcb881e57954?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);">
  <div class="card">
    <div class="photo">
      <%= image_tag "#{@contact.image}", class: "contact-photo", alt: "Your profile photo" %>
    </div>
    <div class="banner"style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1546525506-495a7647977b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80);"></div>
      <div class="personal justify-center">
          <ul>
            <li><strong><%= "#{@contact.first_name} #{@contact.last_name}" %></strong></li>
            <li> <strong>Email:</strong> <%= @contact.email%></li>
            <li><strong>Timezone:</strong> <%= @contact.timezone %></li>
            <li style="color: #fff;">-</li>
            <li>Available hours in <span><%= current_user.timezone %></span>:</li>
            <li style="color: #fff; background: #DC3545">
              <%= @contact.working_hour_start %>:00 | <%= @contact.working_hour_end %>:00
            </li>
          </ul>
      </div>
    <div class="social-media-banner justify-center">
      <a href="https://twitter.com/"  target="_blank"><i class="fa-brands fa-square-twitter"></i></a>
      <a href="https://pt-br.facebook.com/"  target="_blank"><i class="fa-brands fa-square-facebook"></i></a>
      <a href="https://www.instagram.com/"  target="_blank"><i class="fa-brands fa-square-instagram"></i></a>
      <a href="https://www.linkedin.com/"  target="_blank"><i class="fa-brands fa-linkedin"></i></a>
    </div>
  </div>
</div>